pipeline {
    agent { docker { image 'node:22.14.0-alpine3.21' } }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Lint') {
            steps {
                cm 'yarn lint'
            }
        }
    }
}