pipeline {
    agent {
        node {
            label 'testing-pipeline'
            customWorkspace '/jenkins/testing-pipeline'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'yarn'
            }
        }
        stage('Lint') {
            steps {
                sh 'pwd'
                sh 'ls -la'
                sh 'yarn lint'
            }
        }
    }
}