/* Requires the Docker Pipeline plugin */
pipeline {
    agent { docker { image 'node:22.14.0-alpine3.21' } }
    stages {
        stage('build') {
            steps {
                sh 'node --version'
                sh 'echo "Building the application..."'
            }
        }
        stage('test') {
            steps {
                sh 'echo "Running tests..."'
                sh './jenkins/test.sh'
            }
        }
    }
}